alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

server:
  retention: 24h

extraScrapeConfigs: |
  - job_name: otel-collector
    static_configs:
      - targets:
          - otel-collector.monitoring.svc.cluster.local:8889
  - job_name: weather
    static_configs:
      - targets:
          - weather.default.svc.cluster.local:8000
  - job_name: player-projections
    static_configs:
      - targets:
          - player-projections.default.svc.cluster.local:8001
