"""A registered collector gets CI and a GitOps Application with no new file.

That sentence is the whole point of collapsing `.github/workflows/<name>.yml`
and `infra/gitops/argo/<name>.yaml`, and it is the kind of property that decays
quietly: nothing breaks the day somebody adds a per-service workflow "just for
this one", it only stops being true. So it is asserted here rather than
described in a doc.

The load-bearing tests are the two `test_a_synthetic_collector_*` cases. They
invent a collector that exists nowhere in the repo — no `services/` directory,
no committed Helm values, no workflow, no Argo manifest — and assert it still
reaches the CI matrix and the ApplicationSet. Everything else in this file
protects a specific way that could stop being true:

  * a per-service workflow reappearing               (test_no_per_service_*)
  * the matrix quietly becoming "run everything"     (test_*_derived, test_guard_*)
  * the workflow-level `paths:` trigger drifting out of step with the
    generated filters, which silently stops a service's CI
                                                       (test_workflow_trigger_covers_*)
  * the four jobs, their order, or the push-to-main gate being lost in a
    rewrite                                          (test_job_*)

`filters.py` is imported rather than re-implemented. A test that recomputed the
expected filters from its own copy of the rules would pass while agreeing only
with itself.
"""

from __future__ import annotations

import fnmatch
import importlib.util
import json
import re
import sys
import textwrap
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS_DIR = ROOT / ".github" / "workflows"
SERVICES_WORKFLOW = WORKFLOWS_DIR / "services.yml"
APPLICATIONSET = ROOT / "infra" / "gitops" / "argo" / "applicationset.yaml"
ARGO_DIR = ROOT / "infra" / "gitops" / "argo"
REGISTRY_PATH = ROOT / "contracts" / "collector-registry.yaml"
FILTERS_PATH = ROOT / ".github" / "actions" / "changed-services" / "filters.py"

# Services that legitimately keep their own workflow, with the reason. Both are
# outside services.yml's matrix because three of its five jobs do not apply.
STANDALONE_WORKFLOWS = {
    "foundry-cli": "a CLI: no Helm values, no image, no GitOps entry",
    "collector-core": "a library, not a deployable service",
}


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


filters = _load("changed_services_filters", FILTERS_PATH)
fleet = _load("fleet_collectors", ROOT / "scripts" / "collectors.py")

REGISTRY = yaml.safe_load(REGISTRY_PATH.read_text(encoding="utf-8"))
ENTRIES = REGISTRY["collectors"]
IDS = [entry["name"] for entry in ENTRIES]
SERVICES = fleet.services()


def _yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _workflow() -> dict:
    """`services.yml`, with the `on:` key read back as a string.

    PyYAML resolves a bare `on` to the boolean True (YAML 1.1), so the trigger
    block lands under the key `True`, not `"on"`. Normalised here so a test
    reading triggers cannot silently assert against a missing key.
    """
    document = _yaml(SERVICES_WORKFLOW)
    if True in document:
        document["on"] = document.pop(True)
    return document


# ── the per-service files are gone and cannot come back ──────────────────────


@pytest.mark.parametrize("entry", ENTRIES, ids=IDS)
def test_no_per_service_workflow_exists(entry):
    """The failure this prevents is additive, not a break.

    Adding `.github/workflows/<name>.yml` for one collector does not fail
    anything — it just quietly reintroduces the 145-line file that has to be
    kept in step with twenty-five others.
    """
    name = entry["name"]
    assert name not in STANDALONE_WORKFLOWS
    path = WORKFLOWS_DIR / f"{name}.yml"
    assert not path.exists(), (
        f"{path.relative_to(ROOT).as_posix()} exists again. Collectors are "
        f"matrix legs in services.yml, derived from "
        f"contracts/collector-registry.yaml — a per-service workflow is the "
        f"duplication this replaced."
    )


@pytest.mark.parametrize("entry", ENTRIES, ids=IDS)
def test_no_per_service_argo_application_exists(entry):
    name = entry["name"]
    path = ARGO_DIR / f"{name}.yaml"
    assert not path.exists(), (
        f"{path.relative_to(ROOT).as_posix()} exists again. Applications are "
        f"generated by infra/gitops/argo/applicationset.yaml; a hand-written "
        f"one alongside it means two objects claiming the same Application "
        f"name, and the ApplicationSet controller will fight whatever the "
        f"app-of-apps applies."
    )


def test_argo_directory_holds_only_the_app_of_apps_and_the_set():
    """The app-of-apps syncs this whole directory, so anything here is applied."""
    found = sorted(p.name for p in ARGO_DIR.glob("*.yaml"))
    assert found == ["app-of-apps.yaml", "applicationset.yaml"], found


def test_no_service_name_is_hardcoded_in_the_matrix_workflow():
    """The regression guard: the moment a name appears, there are two lists.

    Non-collectors are exempt in the same way they are in
    tests/test_collector_tooling.py — `player-projections` has no registry
    entry, so `scripts/collectors.py` naming it is the only way to deploy it.
    Nothing names it in services.yml today either, but a collector doing so is
    the drift that matters.

    Read from the PARSED document, not the raw text: the file's header comment
    names the four workflows this one replaced, and that is history rather
    than a list. A name in a value — a path filter, a job input, a `run:`
    body — is the real thing being prevented, and comments do not survive
    `safe_load`.
    """
    text = yaml.safe_dump(_workflow())
    named = sorted(
        entry["name"]
        for entry in ENTRIES
        if re.search(rf"(?<![\w-]){re.escape(entry['name'])}(?![\w-])", text)
    )
    assert not named, (
        f".github/workflows/services.yml names collector(s) {named}. Its "
        f"matrix is supposed to be computed by "
        f".github/actions/changed-services from the registry."
    )


def test_no_service_name_is_hardcoded_in_the_applicationset():
    text = APPLICATIONSET.read_text(encoding="utf-8")
    # The header comment names the four manifests this file replaced, as
    # history. Only the spec is checked — a name there is a real list.
    spec = yaml.safe_dump(_yaml(APPLICATIONSET))
    named = sorted(
        entry["name"]
        for entry in ENTRIES
        if re.search(rf"(?<![\w-]){re.escape(entry['name'])}(?![\w-])", spec)
    )
    assert not named, (
        f"infra/gitops/argo/applicationset.yaml's spec names {named}. The git "
        f"directory generator is supposed to discover services from "
        f"helm/values/*, holding no list of its own."
    )
    assert text, "file is empty"


# ── the acceptance criterion, as code ────────────────────────────────────────


def _synthetic_fleet(tmp_path: Path):
    """A registry + Helm values tree holding one collector, invented here.

    Mirrors tests/test_collector_tooling.py's fixture so both suites prove the
    same thing about their own consumer of `scripts/collectors.py`.
    """
    registry = tmp_path / "collector-registry.yaml"
    registry.write_text(
        textwrap.dedent("""\
            collectors:
              - name: throwaway-signal
                path: /collectors/throwaway-signal
                stage: 8Z
                cadence_class: weekly
                envelope_version: 1
                signal_types: [throwaway_probe]
                scope_aware: false
                depends_on: []
            """),
        encoding="utf-8",
    )
    values_dir = tmp_path / "values"
    for name, port, collector in (
        ("throwaway-signal", 8099, True),
        ("player-projections", 8001, False),
    ):
        service_dir = values_dir / name
        service_dir.mkdir(parents=True)
        document: dict = {
            "service": {"name": name, "port": port},
            "containerPort": port,
        }
        if collector:
            document["extraEnv"] = [
                {
                    "name": "COLLECTOR_TOKEN",
                    "valueFrom": {
                        "secretKeyRef": {"name": f"{name}-token", "key": "token"}
                    },
                },
                {"name": "CAPTURE_ENABLED", "value": "true"},
            ]
        (service_dir / "values.yaml").write_text(
            yaml.safe_dump(document), encoding="utf-8"
        )
    return fleet.services(registry_path=registry, values_dir=values_dir), values_dir


def test_a_synthetic_collector_reaches_the_ci_matrix(tmp_path):
    """Append a registry entry; CI covers it with no workflow file.

    `throwaway-signal` has no services/ directory, no committed Helm values and
    no workflow anywhere in this repo.
    """
    synthetic, _ = _synthetic_fleet(tmp_path)
    rules, entries = filters.build(synthetic)

    assert "throwaway-signal" in rules, (
        "a registered collector got no paths-filter rule, so its jobs would "
        "never be selected and its CI would silently never run"
    )
    assert rules["throwaway-signal"] == [
        "services/throwaway-signal/**",
        "helm/values/throwaway-signal/**",
        "libs/**",
        *filters.SHARED_PATHS,
    ]

    leg = entries["throwaway-signal"]
    assert leg == {
        "name": "throwaway-signal",
        "package": "throwaway_signal",
        # A collector builds from the repo root without being told to.
        "context": ".",
        "image": "ghcr.io/kakhavai/foundry/throwaway-signal",
    }

    # And the whole matrix is valid JSON, which is how the workflow consumes it.
    assert json.loads(json.dumps(list(entries.values())))


def test_a_synthetic_collector_is_generated_by_the_applicationset(tmp_path):
    """The Argo half: a values directory is all the generator needs.

    The git directory generator globs `helm/values/*`, so "covered" means the
    collector's values directory matches that pattern. Asserted against the
    pattern read out of the committed manifest, not a copy of it.
    """
    _, values_dir = _synthetic_fleet(tmp_path)
    pattern = _generator_path()

    matched = {
        directory.name
        for directory in values_dir.iterdir()
        if fnmatch.fnmatch(f"helm/values/{directory.name}", pattern)
    }
    assert "throwaway-signal" in matched, (
        f"the ApplicationSet generator pattern {pattern!r} does not match a "
        f"new collector's helm/values/ directory, so no Application would be "
        f"generated for it"
    )


def _generator_path() -> str:
    generators = _yaml(APPLICATIONSET)["spec"]["generators"]
    git_generators = [g["git"] for g in generators if "git" in g]
    assert len(git_generators) == 1, "expected exactly one git generator"
    directories = git_generators[0]["directories"]
    assert len(directories) == 1, "expected exactly one directory pattern"
    return directories[0]["path"]


# ── every real service is actually covered, both ways ────────────────────────


@pytest.mark.parametrize("service", SERVICES, ids=[s.name for s in SERVICES])
def test_every_deployed_service_is_covered_by_ci_and_by_argo(service):
    rules, entries = filters.build(SERVICES)
    assert service.name in rules and service.name in entries

    values_dir = ROOT / "helm" / "values" / service.name
    assert values_dir.is_dir(), (
        f"{service.name} has no helm/values/ directory, so the ApplicationSet's "
        f"git directory generator cannot discover it"
    )
    assert fnmatch.fnmatch(f"helm/values/{service.name}", _generator_path())

    # The ApplicationSet points every generated app at this second values file.
    # A missing one renders as a FAILED Application, not an absent one.
    tag_values = (
        ROOT / "infra" / "gitops" / "envs" / "local" / service.name / "values.yaml"
    )
    assert tag_values.exists(), (
        f"{service.name} has no {tag_values.relative_to(ROOT).as_posix()} — the "
        f"generated Application references it as a valueFile and will fail to "
        f"render without it"
    )


def test_helm_values_holds_no_directory_without_a_service():
    """Reverse direction: the generator would build an Application for it.

    `helm/values/*` is the generator's whole input, so a stray directory there
    becomes a real Application pointing at a chart with no image.
    """
    known = {service.name for service in SERVICES}
    found = {d.name for d in (ROOT / "helm" / "values").iterdir() if d.is_dir()}
    assert found == known, (
        f"helm/values/ and the deployable fleet disagree: "
        f"only-in-helm={sorted(found - known)}, only-in-fleet={sorted(known - found)}"
    )


# ── the matrix workflow keeps the shape CLAUDE.md documents ──────────────────


def test_workflow_is_parseable_yaml():
    assert _workflow()["jobs"], SERVICES_WORKFLOW


def test_the_four_documented_jobs_survive():
    """CLAUDE.md's "How CI Works" names these, and build-push needing the
    other three is the part that keeps a broken service from being pushed."""
    jobs = _workflow()["jobs"]
    for job in ("lint", "test", "helm-lint", "build-push"):
        assert job in jobs, f"services.yml lost the {job!r} job"
    assert set(jobs["build-push"]["needs"]) >= {"lint", "test", "helm-lint"}


@pytest.mark.parametrize("job", ["build-push", "update-gitops-tag"])
def test_deploy_jobs_run_only_on_push_to_main(job):
    condition = _workflow()["jobs"][job]["if"]
    assert "refs/heads/main" in condition
    assert "github.event_name == 'push'" in condition


def test_update_gitops_tag_still_needs_build_push():
    assert "build-push" in _workflow()["jobs"]["update-gitops-tag"]["needs"]


@pytest.mark.parametrize(
    "job",
    ["lint", "test", "helm-lint", "runtime-imports", "build-push", "update-gitops-tag"],
)
def test_every_matrix_job_is_derived_from_the_changes_job(job):
    """The anti-"run everything always" guard.

    A matrix hardcoded to the full fleet would pass every other test in this
    file while running 26 services' jobs on a one-line diff.
    """
    definition = _workflow()["jobs"][job]
    matrix = definition["strategy"]["matrix"]["service"]
    assert "needs.changes.outputs.services" in matrix, (
        f"{job}'s matrix is not computed from the changes job, so it no longer "
        f"path-filters — every service would run on every PR"
    )
    assert "changes" in definition["needs"]


@pytest.mark.parametrize(
    "job",
    ["lint", "test", "helm-lint", "runtime-imports", "build-push", "update-gitops-tag"],
)
def test_every_matrix_job_guards_against_an_empty_matrix(job):
    """An empty matrix vector is a workflow ERROR in GitHub Actions, not a
    skipped job. Without this guard, every PR that touches no service — a
    docs-only PR — fails the whole workflow rather than skipping it."""
    condition = _workflow()["jobs"][job]["if"]
    assert "needs.changes.outputs.services != '[]'" in condition, (
        f"{job} has no empty-matrix guard; a diff affecting no service would "
        f"fail the run instead of skipping it"
    )


def test_changes_job_uses_the_shared_action():
    steps = _workflow()["jobs"]["changes"]["steps"]
    assert any(
        step.get("uses") == "./.github/actions/changed-services" for step in steps
    ), "the changes job no longer computes the matrix from the registry"


def test_workflow_trigger_covers_every_filter_path():
    """The silent-failure guard, and the reason this test exists at all.

    `services.yml` has a workflow-level `paths:` trigger so the gitops bot's
    image-tag commits do not start a run. That list must remain a SUPERSET of
    every path any per-service filter names — a path filtered by
    changed-services but not present here never reaches the filter, because
    the workflow never starts. The symptom is not a failure; it is that a
    service's CI stops running and nobody notices.
    """
    triggers = _workflow()["on"]
    rules, _ = filters.build(SERVICES)
    every_filtered_path = {path for paths in rules.values() for path in paths}

    for event in ("pull_request", "push"):
        declared = set(triggers[event]["paths"])
        for path in sorted(every_filtered_path):
            assert any(_covers(prefix, path) for prefix in declared), (
                f"{event}: the workflow-level paths trigger does not cover "
                f"{path!r}, so a change to it never starts the workflow and "
                f"the filter that names it can never match"
            )


def _covers(declared: str, path: str) -> bool:
    """Whether a trigger glob subsumes a filter glob.

    Only the two shapes actually used: an exact match, or a `dir/**` prefix
    that contains the filtered path.
    """
    if declared == path:
        return True
    if declared.endswith("/**"):
        return path.startswith(declared[: -len("**")])
    return False


# ── the ApplicationSet reproduces what the hand-written manifests did ────────


def test_generated_application_keeps_the_gitops_guarantees():
    """CLAUDE.md's "ArgoCD / GitOps Behavior" rests on all three of these.

    Losing selfHeal or prune would not fail a sync — it would quietly stop
    reverting manual cluster edits, which is the behaviour the whole GitOps
    section describes.
    """
    template = _yaml(APPLICATIONSET)["spec"]["template"]
    automated = template["spec"]["syncPolicy"]["automated"]
    assert automated["prune"] is True
    assert automated["selfHeal"] is True
    assert template["spec"]["source"]["targetRevision"] == "main"


def test_generated_application_matches_the_manifests_it_replaced():
    """The specs are byte-identical modulo the name — pinned so a later edit
    to the template cannot silently change what is deployed.

    These literals are the previous contents of
    infra/gitops/argo/<service>.yaml, which no longer exist to diff against.
    """
    template = _yaml(APPLICATIONSET)["spec"]["template"]
    name = "{{.path.basename}}"

    assert template["metadata"]["name"] == name
    assert template["metadata"]["namespace"] == "argocd"
    assert template["metadata"]["finalizers"] == ["resources-finalizer.argocd.io"]

    spec = template["spec"]
    assert spec["project"] == "default"
    assert spec["source"] == {
        "repoURL": "https://github.com/kakhavai/foundry",
        "targetRevision": "main",
        "path": "helm/charts/generic-service",
        "helm": {
            "valueFiles": [
                f"/helm/values/{name}/values.yaml",
                f"/infra/gitops/envs/local/{name}/values.yaml",
            ]
        },
    }
    assert spec["destination"] == {
        "server": "https://kubernetes.default.svc",
        "namespace": "default",
    }
    assert spec["syncPolicy"]["syncOptions"] == ["CreateNamespace=true"]


def test_applicationset_uses_gotemplate_with_strict_missing_keys():
    """`missingkey=error` is why a typo'd field fails the generator instead of
    producing an Application named "" or a valueFile path with a hole in it."""
    spec = _yaml(APPLICATIONSET)["spec"]
    assert spec["goTemplate"] is True
    assert "missingkey=error" in spec["goTemplateOptions"]


def test_app_of_apps_still_syncs_the_applicationset():
    """The ApplicationSet has to be applied by something. The app-of-apps
    syncs infra/gitops/argo/ with `exclude: app-of-apps.yaml`, so it picks up
    applicationset.yaml — but only while that exclusion stays narrow."""
    app_of_apps = _yaml(ARGO_DIR / "app-of-apps.yaml")
    source = app_of_apps["spec"]["source"]
    assert source["path"] == "infra/gitops/argo"
    assert source["directory"]["exclude"] == "app-of-apps.yaml", (
        "the app-of-apps exclusion changed; if it excludes applicationset.yaml "
        "nothing applies the ApplicationSet and every Application disappears"
    )


# ── the standalone workflows are deliberate, not leftovers ───────────────────


@pytest.mark.parametrize("name", sorted(STANDALONE_WORKFLOWS))
def test_standalone_workflows_still_exist(name):
    """Documented exceptions, so their disappearance is a decision not a slip."""
    assert (WORKFLOWS_DIR / f"{name}.yml").exists(), (
        f"{name}.yml is gone — it is outside services.yml's matrix because "
        f"{STANDALONE_WORKFLOWS[name]}, so nothing else runs its tests"
    )
