service:
  name: weather
  port: 8000

image:
  repository: ghcr.io/kakhavai/foundry/weather

containerPort: 8000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

otel:
  resourceAttributes: "service.name=weather,service.namespace=foundry"

grafanaAnnotations:
  enabled: true
