apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-service.fullname" . }}-config
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.endpoint | quote }}
  OTEL_SERVICE_NAME: {{ .Values.service.name | quote }}
  {{- if .Values.otel.resourceAttributes }}
  OTEL_RESOURCE_ATTRIBUTES: {{ .Values.otel.resourceAttributes | quote }}
  {{- end }}
