apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: player-identity
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/kakhavai/foundry
    targetRevision: main
    path: helm/charts/generic-service
    helm:
      valueFiles:
        - /helm/values/player-identity/values.yaml
        - /infra/gitops/envs/local/player-identity/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
