replicaCount: 1

image:
  repository: ghcr.io/kakhavai/foundry/github-stats
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8000
  nodePort: 30080

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

otel:
  endpoint: "http://otel-collector.monitoring.svc.cluster.local:4317"
