apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-stats.fullname" . }}
  labels:
    {{- include "github-stats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "github-stats.selectorLabels" . | nindent 4 }}
