STADIUMS: dict[str, dict] = {
    "arrowhead": {
        "id": "arrowhead",
        "name": "Arrowhead Stadium",
        "team": "Kansas City Chiefs",
        "city": "Kansas City, MO",
        "latitude": 39.0489,
        "longitude": -94.4839,
    },
    "highmark": {
        "id": "highmark",
        "name": "Highmark Stadium",
        "team": "Buffalo Bills",
        "city": "Orchard Park, NY",
        "latitude": 42.7738,
        "longitude": -78.7870,
    },
    "lambeau": {
        "id": "lambeau",
        "name": "Lambeau Field",
        "team": "Green Bay Packers",
        "city": "Green Bay, WI",
        "latitude": 44.5013,
        "longitude": -88.0622,
    },
    "gillette": {
        "id": "gillette",
        "name": "Gillette Stadium",
        "team": "New England Patriots",
        "city": "Foxborough, MA",
        "latitude": 42.0909,
        "longitude": -71.2643,
    },
    "metlife": {
        "id": "metlife",
        "name": "MetLife Stadium",
        "team": "New York Giants / Jets",
        "city": "East Rutherford, NJ",
        "latitude": 40.8135,
        "longitude": -74.0745,
    },
    "lincoln-financial": {
        "id": "lincoln-financial",
        "name": "Lincoln Financial Field",
        "team": "Philadelphia Eagles",
        "city": "Philadelphia, PA",
        "latitude": 39.9008,
        "longitude": -75.1675,
    },
    "bank-of-america": {
        "id": "bank-of-america",
        "name": "Bank of America Stadium",
        "team": "Carolina Panthers",
        "city": "Charlotte, NC",
        "latitude": 35.2258,
        "longitude": -80.8528,
    },
    "mercedes-benz": {
        "id": "mercedes-benz",
        "name": "Mercedes-Benz Stadium",
        "team": "Atlanta Falcons",
        "city": "Atlanta, GA",
        "latitude": 33.7554,
        "longitude": -84.4010,
    },
    "raymond-james": {
        "id": "raymond-james",
        "name": "Raymond James Stadium",
        "team": "Tampa Bay Buccaneers",
        "city": "Tampa, FL",
        "latitude": 27.9759,
        "longitude": -82.5033,
    },
    "soldier-field": {
        "id": "soldier-field",
        "name": "Soldier Field",
        "team": "Chicago Bears",
        "city": "Chicago, IL",
        "latitude": 41.8623,
        "longitude": -87.6167,
    },
    "us-bank": {
        "id": "us-bank",
        "name": "U.S. Bank Stadium",
        "team": "Minnesota Vikings",
        "city": "Minneapolis, MN",
        "latitude": 44.9737,
        "longitude": -93.2577,
    },
    "ford-field": {
        "id": "ford-field",
        "name": "Ford Field",
        "team": "Detroit Lions",
        "city": "Detroit, MI",
        "latitude": 42.3400,
        "longitude": -83.0456,
    },
    "paycor": {
        "id": "paycor",
        "name": "Paycor Stadium",
        "team": "Cincinnati Bengals",
        "city": "Cincinnati, OH",
        "latitude": 39.0954,
        "longitude": -84.5160,
    },
    "huntington-bank": {
        "id": "huntington-bank",
        "name": "Huntington Bank Field",
        "team": "Cleveland Browns",
        "city": "Cleveland, OH",
        "latitude": 41.5061,
        "longitude": -81.6995,
    },
    "acrisure": {
        "id": "acrisure",
        "name": "Acrisure Stadium",
        "team": "Pittsburgh Steelers",
        "city": "Pittsburgh, PA",
        "latitude": 40.4468,
        "longitude": -80.0158,
    },
    "mt-bank": {
        "id": "mt-bank",
        "name": "M&T Bank Stadium",
        "team": "Baltimore Ravens",
        "city": "Baltimore, MD",
        "latitude": 39.2779,
        "longitude": -76.6227,
    },
    "northwest": {
        "id": "northwest",
        "name": "Northwest Stadium",
        "team": "Washington Commanders",
        "city": "Landover, MD",
        "latitude": 38.9076,
        "longitude": -76.8645,
    },
    "att": {
        "id": "att",
        "name": "AT&T Stadium",
        "team": "Dallas Cowboys",
        "city": "Arlington, TX",
        "latitude": 32.7473,
        "longitude": -97.0945,
    },
    "allegiant": {
        "id": "allegiant",
        "name": "Allegiant Stadium",
        "team": "Las Vegas Raiders",
        "city": "Paradise, NV",
        "latitude": 36.0909,
        "longitude": -115.1833,
    },
    "sofi": {
        "id": "sofi",
        "name": "SoFi Stadium",
        "team": "Los Angeles Rams / Chargers",
        "city": "Inglewood, CA",
        "latitude": 33.9535,
        "longitude": -118.3392,
    },
    "lumen-field": {
        "id": "lumen-field",
        "name": "Lumen Field",
        "team": "Seattle Seahawks",
        "city": "Seattle, WA",
        "latitude": 47.5952,
        "longitude": -122.3316,
    },
    "levis": {
        "id": "levis",
        "name": "Levi's Stadium",
        "team": "San Francisco 49ers",
        "city": "Santa Clara, CA",
        "latitude": 37.4033,
        "longitude": -121.9694,
    },
    "state-farm": {
        "id": "state-farm",
        "name": "State Farm Stadium",
        "team": "Arizona Cardinals",
        "city": "Glendale, AZ",
        "latitude": 33.5276,
        "longitude": -112.2626,
    },
    "empower-field": {
        "id": "empower-field",
        "name": "Empower Field at Mile High",
        "team": "Denver Broncos",
        "city": "Denver, CO",
        "latitude": 39.7439,
        "longitude": -105.0201,
    },
    "nissan": {
        "id": "nissan",
        "name": "Nissan Stadium",
        "team": "Tennessee Titans",
        "city": "Nashville, TN",
        "latitude": 36.1665,
        "longitude": -86.7713,
    },
    "lucas-oil": {
        "id": "lucas-oil",
        "name": "Lucas Oil Stadium",
        "team": "Indianapolis Colts",
        "city": "Indianapolis, IN",
        "latitude": 39.7601,
        "longitude": -86.1639,
    },
    "evo": {
        "id": "evo",
        "name": "EverBank Stadium",
        "team": "Jacksonville Jaguars",
        "city": "Jacksonville, FL",
        "latitude": 30.3239,
        "longitude": -81.6373,
    },
    "hard-rock": {
        "id": "hard-rock",
        "name": "Hard Rock Stadium",
        "team": "Miami Dolphins",
        "city": "Miami Gardens, FL",
        "latitude": 25.9580,
        "longitude": -80.2388,
    },
    "caesars-superdome": {
        "id": "caesars-superdome",
        "name": "Caesars Superdome",
        "team": "New Orleans Saints",
        "city": "New Orleans, LA",
        "latitude": 29.9511,
        "longitude": -90.0812,
    },
    "nrg": {
        "id": "nrg",
        "name": "NRG Stadium",
        "team": "Houston Texans",
        "city": "Houston, TX",
        "latitude": 29.6847,
        "longitude": -95.4107,
    },
}
