STADIUMS: dict[str, dict] = {
    "arrowhead": {
        "id": "arrowhead",
        "name": "Arrowhead Stadium",
        "team": "Kansas City Chiefs",
        "city": "Kansas City, MO",
        "latitude": 39.0489,
        "longitude": -94.4839,
        "stadium_id": "KAN00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "highmark": {
        "id": "highmark",
        "name": "Highmark Stadium",
        "team": "Buffalo Bills",
        "city": "Orchard Park, NY",
        "latitude": 42.7738,
        "longitude": -78.7870,
        "stadium_id": "BUF00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "lambeau": {
        "id": "lambeau",
        "name": "Lambeau Field",
        "team": "Green Bay Packers",
        "city": "Green Bay, WI",
        "latitude": 44.5013,
        "longitude": -88.0622,
        "stadium_id": "GNB00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "gillette": {
        "id": "gillette",
        "name": "Gillette Stadium",
        "team": "New England Patriots",
        "city": "Foxborough, MA",
        "latitude": 42.0909,
        "longitude": -71.2643,
        "stadium_id": "BOS00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "metlife": {
        "id": "metlife",
        "name": "MetLife Stadium",
        "team": "New York Giants / Jets",
        "city": "East Rutherford, NJ",
        "latitude": 40.8135,
        "longitude": -74.0745,
        "stadium_id": "NYC01",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "lincoln-financial": {
        "id": "lincoln-financial",
        "name": "Lincoln Financial Field",
        "team": "Philadelphia Eagles",
        "city": "Philadelphia, PA",
        "latitude": 39.9008,
        "longitude": -75.1675,
        "stadium_id": "PHI00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "bank-of-america": {
        "id": "bank-of-america",
        "name": "Bank of America Stadium",
        "team": "Carolina Panthers",
        "city": "Charlotte, NC",
        "latitude": 35.2258,
        "longitude": -80.8528,
        "stadium_id": "CAR00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "mercedes-benz": {
        "id": "mercedes-benz",
        "name": "Mercedes-Benz Stadium",
        "team": "Atlanta Falcons",
        "city": "Atlanta, GA",
        "latitude": 33.7554,
        "longitude": -84.4010,
        "stadium_id": "ATL97",
        "roof_type": "retractable",
        "enclosure_class": "enclosed",
    },
    "raymond-james": {
        "id": "raymond-james",
        "name": "Raymond James Stadium",
        "team": "Tampa Bay Buccaneers",
        "city": "Tampa, FL",
        "latitude": 27.9759,
        "longitude": -82.5033,
        "stadium_id": "TAM00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "soldier-field": {
        "id": "soldier-field",
        "name": "Soldier Field",
        "team": "Chicago Bears",
        "city": "Chicago, IL",
        "latitude": 41.8623,
        "longitude": -87.6167,
        "stadium_id": "CHI98",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "us-bank": {
        "id": "us-bank",
        "name": "U.S. Bank Stadium",
        "team": "Minnesota Vikings",
        "city": "Minneapolis, MN",
        "latitude": 44.9737,
        "longitude": -93.2577,
        "stadium_id": "MIN01",
        "roof_type": "fixed_dome",
        "enclosure_class": "enclosed",
    },
    "ford-field": {
        "id": "ford-field",
        "name": "Ford Field",
        "team": "Detroit Lions",
        "city": "Detroit, MI",
        "latitude": 42.3400,
        "longitude": -83.0456,
        "stadium_id": "DET00",
        "roof_type": "fixed_dome",
        "enclosure_class": "enclosed",
    },
    "paycor": {
        "id": "paycor",
        "name": "Paycor Stadium",
        "team": "Cincinnati Bengals",
        "city": "Cincinnati, OH",
        "latitude": 39.0954,
        "longitude": -84.5160,
        "stadium_id": "CIN00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "huntington-bank": {
        "id": "huntington-bank",
        "name": "Huntington Bank Field",
        "team": "Cleveland Browns",
        "city": "Cleveland, OH",
        "latitude": 41.5061,
        "longitude": -81.6995,
        "stadium_id": "CLE00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "acrisure": {
        "id": "acrisure",
        "name": "Acrisure Stadium",
        "team": "Pittsburgh Steelers",
        "city": "Pittsburgh, PA",
        "latitude": 40.4468,
        "longitude": -80.0158,
        "stadium_id": "PIT00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "mt-bank": {
        "id": "mt-bank",
        "name": "M&T Bank Stadium",
        "team": "Baltimore Ravens",
        "city": "Baltimore, MD",
        "latitude": 39.2779,
        "longitude": -76.6227,
        "stadium_id": "BAL00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "northwest": {
        "id": "northwest",
        "name": "Northwest Stadium",
        "team": "Washington Commanders",
        "city": "Landover, MD",
        "latitude": 38.9076,
        "longitude": -76.8645,
        "stadium_id": "WAS00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "att": {
        "id": "att",
        "name": "AT&T Stadium",
        "team": "Dallas Cowboys",
        "city": "Arlington, TX",
        "latitude": 32.7473,
        "longitude": -97.0945,
        "stadium_id": "DAL00",
        "roof_type": "retractable",
        "enclosure_class": "enclosed",
    },
    "allegiant": {
        "id": "allegiant",
        "name": "Allegiant Stadium",
        "team": "Las Vegas Raiders",
        "city": "Paradise, NV",
        "latitude": 36.0909,
        "longitude": -115.1833,
        "stadium_id": "VEG00",
        "roof_type": "fixed_dome",
        "enclosure_class": "enclosed",
    },
    "sofi": {
        "id": "sofi",
        "name": "SoFi Stadium",
        "team": "Los Angeles Rams / Chargers",
        "city": "Inglewood, CA",
        "latitude": 33.9535,
        "longitude": -118.3392,
        "stadium_id": "LAX01",
        "roof_type": "fixed_dome",
        "enclosure_class": "enclosed",
    },
    "lumen-field": {
        "id": "lumen-field",
        "name": "Lumen Field",
        "team": "Seattle Seahawks",
        "city": "Seattle, WA",
        "latitude": 47.5952,
        "longitude": -122.3316,
        "stadium_id": "SEA00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "levis": {
        "id": "levis",
        "name": "Levi's Stadium",
        "team": "San Francisco 49ers",
        "city": "Santa Clara, CA",
        "latitude": 37.4033,
        "longitude": -121.9694,
        "stadium_id": "SFO01",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "state-farm": {
        "id": "state-farm",
        "name": "State Farm Stadium",
        "team": "Arizona Cardinals",
        "city": "Glendale, AZ",
        "latitude": 33.5276,
        "longitude": -112.2626,
        "stadium_id": "PHO00",
        "roof_type": "retractable",
        "enclosure_class": "enclosed",
    },
    "empower-field": {
        "id": "empower-field",
        "name": "Empower Field at Mile High",
        "team": "Denver Broncos",
        "city": "Denver, CO",
        "latitude": 39.7439,
        "longitude": -105.0201,
        "stadium_id": "DEN00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "nissan": {
        "id": "nissan",
        "name": "Nissan Stadium",
        "team": "Tennessee Titans",
        "city": "Nashville, TN",
        "latitude": 36.1665,
        "longitude": -86.7713,
        "stadium_id": "NAS00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "lucas-oil": {
        "id": "lucas-oil",
        "name": "Lucas Oil Stadium",
        "team": "Indianapolis Colts",
        "city": "Indianapolis, IN",
        "latitude": 39.7601,
        "longitude": -86.1639,
        "stadium_id": "IND00",
        "roof_type": "retractable",
        "enclosure_class": "enclosed",
    },
    "evo": {
        "id": "evo",
        "name": "EverBank Stadium",
        "team": "Jacksonville Jaguars",
        "city": "Jacksonville, FL",
        "latitude": 30.3239,
        "longitude": -81.6373,
        "stadium_id": "JAX00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "hard-rock": {
        "id": "hard-rock",
        "name": "Hard Rock Stadium",
        "team": "Miami Dolphins",
        "city": "Miami Gardens, FL",
        "latitude": 25.9580,
        "longitude": -80.2388,
        "stadium_id": "MIA00",
        "roof_type": "open",
        "enclosure_class": "partial",
    },
    "caesars-superdome": {
        "id": "caesars-superdome",
        "name": "Caesars Superdome",
        "team": "New Orleans Saints",
        "city": "New Orleans, LA",
        "latitude": 29.9511,
        "longitude": -90.0812,
        "stadium_id": "NOR00",
        "roof_type": "fixed_dome",
        "enclosure_class": "enclosed",
    },
    "nrg": {
        "id": "nrg",
        "name": "NRG Stadium",
        "team": "Houston Texans",
        "city": "Houston, TX",
        "latitude": 29.6847,
        "longitude": -95.4107,
        "stadium_id": "HOU00",
        "roof_type": "retractable",
        "enclosure_class": "enclosed",
    },
}

# This is a proto-`venue` table. It migrates wholesale into the `venue`
# collector at 8E, at which point `enclosure_class` gets a name that does not
# collide with venue.crowd_noise_profile.enclosure_class — that field describes
# acoustics, this one describes how much the bowl shelters the field from wind.
# Two correlated but distinct properties.

BY_STADIUM_ID: dict[str, dict] = {s["stadium_id"]: s for s in STADIUMS.values()}

# Exactly the venues the schedule feed leaves `roof` empty for before kickoff.
# Membership is what makes an empty roof mean "not yet decided" rather than
# "the feed broke" — without it the two are indistinguishable.
RETRACTABLE_STADIUM_IDS: frozenset[str] = frozenset(
    s["stadium_id"] for s in STADIUMS.values() if s["roof_type"] == "retractable"
)
