service:
  name: github-stats
  port: 8000

image:
  repository: ghcr.io/kakhavai/foundry/github-stats

containerPort: 8000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
