name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      github-stats: ${{ steps.filter.outputs.github-stats }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            github-stats:
              - 'services/github-stats/**'
              - 'helm/charts/github-stats/**'

  github-stats-lint-test:
    needs: changes
    if: needs.changes.outputs.github-stats == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-lint-test
        with:
          working-directory: services/github-stats

  github-stats-helm-lint:
    needs: changes
    if: needs.changes.outputs.github-stats == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/helm-lint
        with:
          chart-path: helm/charts/github-stats
